name: Build and Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # 例如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/image.tar
          tags: base-centos7-py2-java8:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: base-centos7-py2-java8
          path: /tmp/image.tar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/image.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
